services:
  web:
    build: .
    container_name: face-merge-web
    ports:
      - "5001:5000"  # Maps port 5000 inside the container to port 5001 on your host machine
    networks:
      - face-merge-net
    depends_on:
      - mongodb
    volumes:
      - ./app:/app/app  # Maps the app directory to the container's working directory
      # TODO: delete the above line before submitting
    env_file:
      - .env
    environment:
        - MONGO_URI=mongodb://face-merge-mongodb:27017/db

  mongodb:
    image: mongo
    container_name: face-merge-mongodb
    volumes:
      - mongo-data:/data/db
    networks:
      - face-merge-net

  image-classification-api:
    build: ../image_classification_api
    container_name: face-merge-image-classification-api
    ports:
      - "6000:6000"
    networks:
      - face-merge-net
    depends_on:
      - mongodb
    volumes:
      - ../image-classification-api:/app/app
    env_file:
      - .env
    environment:
      - MONGO_URI=mongodb://face-merge-mongodb:27017/api_db
      # in the above line, api_db is the name of the database
      - GUNICORN_WORKERS=7

volumes:
  mongo-data:

networks:
  face-merge-net:
