version: '3'
services:
  web:
    build: .
    container_name: face-merge-web
    ports:
      - "5001:5000"
    networks:
      - face-merge-net
    depends_on:
      - mongodb
    volumes:
      - ./app:/app/app
    env_file:
      - .env
    environment:
      - MONGO_URI=mongodb://root:rootpassword@face-merge-mongodb:27017/db?authSource=admin

  mongodb:
    image: mongo:latest
    container_name: face-merge-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - face-merge-net
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword
    command: mongod --auth

  mongo-express:
    image: mongo-express:latest
    container_name: face-merge-mongo-express
    restart: always
    ports:
      - "8080:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpassword
      - ME_CONFIG_MONGODB_URL=mongodb://root:rootpassword@face-merge-mongodb:27017/?authSource=admin
    networks:
      - face-merge-net
    depends_on:
      - mongodb

  image-classification-api:
    build: ../image_classification_api
    container_name: face-merge-image-classification-api
    ports:
      - "6000:6000"
    networks:
      - face-merge-net
    depends_on:
      - mongodb
    volumes:
      - ../image_classification_api:/app
    env_file:
      - .env
    environment:
      - MONGO_URI=mongodb://root:rootpassword@face-merge-mongodb:27017/api_db?authSource=admin
      - GUNICORN_WORKERS=7

volumes:
  mongo-data:

networks:
  face-merge-net:
    driver: bridge