version: '3'
services:
  web:
    build: .
    container_name: face-merge-web
    ports:
      - "5001:5000"
    networks:
      - face-merge-net
    depends_on:
      - mongodb
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - FLASK_ENV=testing
      - MONGO_URI=mongodb://face-merge-mongodb:27017/testdb
    command: ["python", "-m", "unittest", "discover", "-v", "-s", "tests"]

  mongodb:
    image: mongo
    container_name: face-merge-mongodb
    volumes: []
    tmpfs:
      - /data/db
    networks:
      - face-merge-net

  image-classification-api:
    build: ../image_classification_api
    container_name: face-merge-image-classification-api
    ports:
      - "6000:6000"
    networks:
      - face-merge-net
    depends_on:
      - mongodb
    volumes:
      - ../image_classification_api:/app
    env_file:
      - .env
    environment:
      - MONGO_URI=mongodb://face-merge-mongodb:27017/api_db
      - GUNICORN_WORKERS=7

volumes:
  mongo-data: null

networks:
  face-merge-net: