version: '3'
services:
  web:
    build: .
    container_name: face-merge-web
    ports:
      - "5001:5000"  # Maps port 5000 inside the container to port 5001 on your host machine
    networks:
      - face-merge-net
    depends_on:
      - mongodb
    volumes:
      - ./app:/app/app  # Maps the app directory to the container's working directory
      # TODO: delete the above line before submitting
    env_file:
      - .env  # Default .env file for regular mode
    environment:
      - FLASK_ENV=testing
      - MONGO_URI=mongodb://face-merge-mongodb:27017/testdb  # Note that it is testdb and not db.
      # The above line is the same mongo instance as in docker-compose.yml, but a different database

    command:
      - python -m tests.test_login

  mongodb:
    image: mongo
    container_name: face-merge-mongodb
    volumes: []
    tmpfs:
      - /data/db  # Store data in memory for test mode to prevent persistence
    networks:
      - face-merge-net


volumes:
  mongo-data: null  # This removes the volume definition for tests

networks:
  face-merge-net:

