  version: '3'

  services:
    mongo:
      image: mongo
      container_name: image-classification-db
      volumes:
        - mongo-data:/data/db
      ports:
        - "27017:27017"  # HOST:CONTAINER

    web:
      build: .
      container_name: image-classification-api
      ports:
        - "6000:5000"
      volumes:
        - .:/app
      depends_on:
        - mongo

  volumes:
    mongo-data:
