version: '3'

services:
  mongo:
    image: mongo
    container_name: image-classification-db
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  web:
    image: image_classification_api-web
    working_dir: /app
    ports:
      - "5000:5000"  # TODO: change to 6000 because Stav asked
    depends_on:
      - mongo

volumes:
  mongo-data:
