  services:
    mongo:
      image: mongo
      container_name: image-classification-db
      volumes:
        - mongo-data:/data/db  # this is a named volume
      ports:
        - "27017:27017"  # HOST:CONTAINER

    web:
      build: .
      container_name: image-classification-api
      ports:
        - "6000:6000"
      volumes:
        - .:/app
      depends_on:
        - mongo
      environment:
        - GUNICORN_WORKERS=7
        - MONGO_URI=mongodb://image-classification-db:27017/api_db
      env_file:
        - .env

  volumes:
    mongo-data:
